---
title: "Functions"
author: "Leonor Rui"
date: "2024-10-24"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
library(readxl)
```

## Writing function

As an example, here's a z-score computation

```{r}
x_vec = rnorm(n = 25, mean = 10, sd = 3.5)

(x_vec - mean(x_vec)) / sd(x_vec)
```
Now write a function to do this

```{r}
z_scores = function(x) {
  
  z = (x - mean(x)) / sd(x)
  
  return(z)
}

z_scores(x_vec)
```

Does this always work?

```{r, error=TRUE}
z_scores(3)
## can't compute SD for just one number

z_scores(c("my", "name", "is", "Leonor"))
## can't calculate mean and SD for character variable
```

```{r, error=TRUE}
z_scores = function(x) {
  
  if(!is.numeric(x)) {
    stop("x needs to be numeric")
  }
  
  if(length(x) < 5){
    stop("you need at least 5 numbers to compute the z")
  }
  
  z = (x - mean(x)) / sd(x)
  
  return(z)
}

z_scores(c("my", "name", "is", "Leonor"))
z_scores(3)
z_scores(x_vec)
```

## A new function with Multiple outputs

```{r}
mean_and_sd = function(x){
  
  mean_x = mean(x)
  sd_x = sd(x)
  
  out_df = tibble(
    mean = mean_x,
    sd = sd_x
  )
  
  return(out_df)
}

mean_and_sd(x_vec)
```

## Check stuff using a simulation

```{r}
sim_df = 
  tibble(
    x = rnorm(30, 10, 5)
  )

sim_df |>
  summarize(
    mean = mean(x),
    sd = sd(x)
  )
```

Simulation function to check sample mean and sd:

```{r}
sim_mean_sd = function(samp_size, true_mean, true_sd) {
  sim_df = 
  tibble(
    x = rnorm(samp_size, true_mean, true_sd)
  )

  out_df =
    sim_df |>
    summarize(
      mean = mean(x),
      sd = sd(x)
    )

  return(out_df)
}

sim_mean_sd(30, 4, 12)
## can be in any sequence if use names
sim_mean_sd(true_sd = 12, samp_size = 30, true_mean = 4)
sim_mean_sd(3000, 4, 12)
```

```{r}
sim_mean_sd = function(samp_size, true_mean = 10, true_sd = 5) {
  sim_df = 
  tibble(
    x = rnorm(samp_size, true_mean, true_sd)
  )

  out_df =
    sim_df |>
    summarize(
      mean = mean(x),
      sd = sd(x)
    )

  return(out_df)
}

sim_mean_sd(3000)
```

## Revisit LoTR Words

```{r}
fellowship_df = 
  read_excel("data/LoTR_words.xlsx", range = "B3:D6") |>
  mutate(movie = "fellowship") |>
  janitor::clean_names()

two_towers_df = 
  read_excel("data/LoTR_words.xlsx", range = "F3:H6") |>
  mutate(movie = "two_towers") |>
  janitor::clean_names()

return_king_df = 
  read_excel("data/LoTR_words.xlsx", range = "J3:L6") |>
  mutate(movie = "return_king") |>
  janitor::clean_names()
```

Write a function that reads this data

```{r}
read_df = function(data_road, start_end, movie_name) {
  movie_df = 
    read_excel(data_road, range = start_end) |>
    mutate(movie = movie_name) |>
    janitor::clean_names() |>
    pivot_longer(
      female:male,
      names_to = "sex",
      values_to = "words"
    )
  
  return(movie_df)
}

lotr_df = 
  bind_rows(
    read_df("data/LoTR_words.xlsx", "J3:L6", "return_king"),
    read_df("data/LoTR_words.xlsx", "F3:H6", "two_towers"),
    read_df("data/LoTR_words.xlsx", "B3:D6", "fellowship")
  )
```

## NSDUH

read data from web

```{r}
nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

nsduh_html = read_html(nsduh_url)

marj_table =
  nsduh_html |>
  html_table() |>
  nth(1) |>
  slice(-1) |>
  mutate(drug = "marj")

cocaine_table =
  nsduh_html |>
  html_table() |>
  nth(4) |>
  slice(-1) |>
  mutate(drug = "cocaine")

heroin_table =
  nsduh_html |>
  html_table() |>
  nth(5) |>
  slice(-1) |>
  mutate(drug = "heroin")
```

Write a function that reads the tables

```{r}
read_table = function(html, table_num, drug_name) {
  drug_table = 
    html |>
      html_table() |>
      nth(table_num) |>
      slice(-1) |>
      mutate(drug = drug_name)
  
  return(drug_table)
}

read_table(nsduh_html, 1, "marj")
read_table(nsduh_html, 4, "cocaine")
read_table(nsduh_html, 5, "heroine")
```

```{r}
source("source/nsduh_table_format.R")

bind_rows(
  nsduh_table_format(nsduh_html, 1, "marj"),
  nsduh_table_format(nsduh_html, 4, "cocaine"),
  nsduh_table_format(nsduh_html, 5, "heroine")
)
```








