---
title: "simulations"
author: "Leonor Rui"
date: "2024-10-31"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
library(readxl)
```

## Check stuff using a simulation

```{r}
sim_df = 
  tibble(
    x = rnorm(30, 10, 5)
  )

sim_df |>
  summarize(
    mean = mean(x),
    sd = sd(x)
  )
```

## Simulation function to check sample mean and sd:

```{r}
sim_mean_sd = function(samp_size, true_mean = 10, true_sd = 5) {
  sim_df = 
  tibble(
    x = rnorm(samp_size, true_mean, true_sd)
  )

  out_df =
    sim_df |>
    summarize(
      mean = mean(x),
      sd = sd(x)
    )

  return(out_df)
}
```

run this a lot of times...

```{r}
sim_mean_sd(3000)
```

run this using a for loop?

```{r}
output = vector("list", 1000)

for (i in 1:1000){
  output[[i]] = sim_mean_sd(30)
}

###
bind_rows(output)
###

### sd of mean should be original sample sd/sqrt(n)
bind_rows(output) |>
  summarize(
    ave_mean = mean(mean),
    se_mean = sd(mean)
  )
```

Can I use map instead?

```{r}
sim_res = 
  tibble(
    iter = 1:1000
  ) |>
  mutate(samp_res = map(iter, sim_mean_sd, samp_size = 30)) |>
  unnest(samp_res)
```

Can I try different sample sizes?

```{r}
sim_res = 
  expand_grid(
    n = c(10, 30, 60, 100),
    iter = 1:1000
  ) |>
  mutate(samp_res = map(n, sim_mean_sd)) |>
  unnest(samp_res)
```

```{r}
sim_res |>
  group_by(n) |>
  summarize(
    se = sd(mean)
  )
```

```{r}
sim_res|>
  filter(n == 10) |>
  ggplot(aes(x = mean)) +
  geom_histogram()

sim_res|>
  filter(n == 100) |>
  ggplot(aes(x = mean)) +
  geom_histogram()
```

```{r}
sim_res |>
  mutate(n = str_c("n = ", n),
         n = fct_inorder(n)) |>
  ggplot(aes(x = n, y = mean)) +
  geom_violin()
```

## Simple Linear Regression

```{r}
sim_data = 
  tibble(
    x = rnorm(30, mean = 1, sd = 1),
    y = 2 + 3*x + rnorm(30, 0, 1)
  )

lm_fit = lm(y ~ x, data = sim_data)

sim_data |>
  ggplot(aes(x = x, y = y)) +
  geom_point() +
  stat_smooth(method = lm)
```

Turn this into a function

```{r}
sim_regression = function(n){
  
  sim_data = 
    tibble(
      x = rnorm(n, mean = 1, sd = 1),
      y = 2 + 3*x + rnorm(n, 0, 1)
    )

  lm_fit = lm(y ~ x, data = sim_data)
  
  out_df = 
    tibble(
      beta0_hat = coef(lm_fit)[1],
      beta1_hat = coef(lm_fit)[2]
    )
  
  return(out_df)
}

sim_res = 
  expand_grid(
    sample_size = c(30, 60),
    iter = 1:1000
  ) |>
  mutate(lm_res = map(sample_size, sim_regression)) |>
  unnest(lm_res)

```

```{r}
sim_res |>
  ggplot(aes(x = beta0_hat)) +
  geom_histogram()

sim_res |>
  ggplot(aes(x = beta1_hat)) +
  geom_histogram()

## larger sample size generate samples with smaller SE
sim_res |>
  mutate(sample_size = str_c("n = ", sample_size)) |>
  ggplot(aes(x = sample_size, y = beta1_hat)) +
  geom_boxplot()

sim_res |>
  filter(sample_size == 30) |>
  ggplot(aes(x = beta0_hat, y = beta1_hat)) +
  geom_point()
```

## Birthday problem :(

Let's put people in a room

```{r}
bdays = sample(1:365, size = 10, replace = TRUE)

length(unique(bdays)) <10
```

```{r}
bday_sim = function(n){
  bdays = sample(1:365, size = n, replace = TRUE)

  duplicate = length(unique(bdays)) < n
  
  return(duplicate)
}

bday_sim(50)
```

run this a lot

```{r}
sim_res = 
  expand_grid(
    n = 2:50, 
    iter = 1:10000
  ) |>
  mutate(res = map_lgl(n, bday_sim)) |>
  group_by(n) |>
  summarize(prob = mean(res))

sim_res |>
  ggplot(aes(x = n, y = prob)) +
  geom_line()
```








